import Chat from '../assets/chat.jpg';
import Glass from '../assets/glass.jpg';

// export const cardData = [
export const cardData = [...Array(1)].flatMap(() => [
    // { name: 'Chitchat', content: 'You have a new message!', image: Glass },
    // { name: 'Updates', content: 'Check out the latest news.', image: Chat },
    // { name: 'Alerts', content: 'Security update required!', image: Glass },
    // { name: 'Reminders', content: 'Meeting at 3:00 PM.', image: Glass },
    // { name: 'Tasks', content: 'Complete your assignments.', image: Glass },
    // { name: 'Notifications', content: 'You have 5 new alerts.' },
    // { name: 'Promotions', content: 'Exclusive discounts inside!' },
    // { name: 'Events', content: 'Upcoming event this weekend.' },
    // { name: 'Support', content: 'Chat with our team now.' },
    // { name: 'Offers', content: 'Limited-time sale!' },
    { name: 'Chitchat', content: 'You have a new message!', image: Glass },
    { name: 'Updates', content: 'Check out the latest news.', image: Chat },
    { name: 'Alerts', content: 'Security update required!', image: Glass },
    { name: 'Reminders', content: 'Meeting at 3:00 PM.', image: Glass },
    { name: 'Tasks', content: 'Complete your assignments.', image: Glass },
    { name: 'Notifications', content: 'You have 5 new alerts.' },
    { name: 'Promotions', content: 'Exclusive discounts inside!' },
    { name: 'Events', content: 'Upcoming event this weekend.' },
    { name: 'Support', content: 'Chat with our team now.' },
    { name: 'Offers', content: 'Limited-time sale!' },
    { name: 'Chitchat', content: 'You have a new message!' },
    { name: 'Updates', content: 'Check out the latest news.', image: Chat },
    { name: 'Alerts', content: 'Security update required!' },
    { name: 'Reminders', content: 'Meeting at 3:00 PM.' },
    { name: 'Tasks', content: 'Complete your assignments.' },
    { name: 'Notifications', content: 'You have 5 new alerts.' },
    { name: 'Promotions', content: 'Exclusive discounts inside!' },
    { name: 'Events', content: 'Upcoming event this weekend.' },
    { name: 'Support', content: 'Chat with our team now.' },
    { name: 'Offers', content: 'Limited-time sale!' },
    { name: 'Chitchat', content: 'You have a new message!' },
    { name: 'Updates', content: 'Check out the latest news.', image: Chat },
    { name: 'Alerts', content: 'Security update required!' },
    { name: 'Reminders', content: 'Meeting at 3:00 PM.' },
    { name: 'Tasks', content: 'Complete your assignments.' },
    { name: 'Notifications', content: 'You have 5 new alerts.' },
    { name: 'Promotions', content: 'Exclusive discounts inside!' },
    { name: 'Events', content: 'Upcoming event this weekend.' },
    { name: 'Support', content: 'Chat with our team now.' },
    { name: 'Offers', content: 'Limited-time sale!' },
    { name: 'Chitchat', content: 'You have a new message!' },
    { name: 'Updates', content: 'Check out the latest news.', image: Chat },
    { name: 'Alerts', content: 'Security update required!' },
    { name: 'Reminders', content: 'Meeting at 3:00 PM.' },
    { name: 'Tasks', content: 'Complete your assignments.' },
    { name: 'Notifications', content: 'You have 5 new alerts.' },
    { name: 'Promotions', content: 'Exclusive discounts inside!' },
    { name: 'Events', content: 'Upcoming event this weekend.' },
    { name: 'Support', content: 'Chat with our team now.' },
    { name: 'Offers', content: 'Limited-time sale!' }
    // ];
]);